# frozen_string_literal: true

source "https://rubygems.org"

repo_name = "Brightcoders-Bootcamps/kata-04-the-bowling-game-team03-kata04-1.git"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rspec"
gem 'rake'
gem 'rubycritic'
gem 'rubycritic-small-badge', :require => false
gem 'sandi_meter'